version: '3.8'

services:
  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      TOMORROW_IO_API_KEY: "aAmCqeVKOdHDbw16oLPjuo9tsSZkzMei"
      DELAY_IN_SECONDS: 300000